onlyBuiltDependencies:
    - "@scarf/scarf"
    - "@tree-sitter-grammars/tree-sitter-yaml"
    - core-js
    - core-js-pure
    - msw
    - protobufjs
    - sharp
    - tree-sitter
    - tree-sitter-json
    - unrs-resolver
    - vue-demi
